#line 2 "tokeniser/tokeniser.yy.cpp"

#line 4 "tokeniser/tokeniser.yy.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 86
#define YY_END_OF_BUFFER 87
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[232] =
    {   0,
        0,    0,   87,   86,   83,   82,   84,   64,   86,   86,
       38,   39,   71,   72,   36,   34,   67,   35,   86,   37,
       80,   77,   68,   70,   61,   44,   62,   69,   33,   75,
       76,   41,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   73,   40,   74,
       63,   58,    0,    0,   49,   55,   50,   47,   65,   45,
       66,   46,   78,   48,   78,   80,    0,    0,   80,    0,
       77,   77,   42,   59,   57,   60,   43,   33,   52,   33,
       33,   33,   33,   33,   33,    8,   33,   33,   33,   33,
       33,   33,   16,   33,   33,   33,   33,   33,   33,   33,

       33,   33,   33,   33,   51,   56,   81,    0,    0,   78,
       78,   78,   79,   53,   54,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   14,   33,   17,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,    0,   78,   79,    1,   33,    3,
        4,   33,   33,   33,   33,   10,   11,   33,   33,   15,
       18,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   30,   33,   33,    0,    2,    5,   33,   33,
       33,   33,   13,   33,   33,   21,   33,   33,   33,   33,
       33,   33,   28,   33,   33,   32,    0,   33,   33,    9,

       12,   33,   20,   22,   23,   24,   25,   26,   33,   33,
       33,   85,   33,    7,   33,   27,   33,   33,    0,    6,
       19,   29,   31,   85,   85,   85,   85,    0,    0,    0,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   23,   23,   24,   24,   25,   26,   27,
       28,   29,   30,    1,   31,   31,   31,   31,   32,   33,
       34,   34,   34,   34,   34,   35,   34,   34,   34,   34,
       34,   34,   34,   34,   36,   34,   34,   37,   34,   34,
       38,    1,   39,   40,   34,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   34,   50,   51,   52,   53,
       54,   55,   34,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   65,   66,   67,   68,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[69] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    1,    1,    1,    1,    1,    1,
        4,    4,    3,    5,    6,    5,    5,    1,    1,    1,
        4,    4,    4,    4,    4,    3,    5,    5,    5,    5,
        6,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[238] =
    {   0,
        0,    0,  379,  380,  380,  380,  380,  350,    0,  373,
      348,   60,  380,  380,  347,   57,  380,   56,   54,  346,
       73,  120,  380,  380,   52,  345,   53,  380,    0,  380,
      380,  344,  312,  314,   58,   53,   49,   32,  315,   67,
      314,  322,   67,  303,  312,  310,  315,  380,   91,  380,
      380,  380,  356,  127,  380,  380,  380,  380,  380,  380,
      380,  380,  162,  380,  196,   64,  180,  140,  380,    0,
        0,  380,  333,  380,  380,  380,  332,    0,  380,  301,
      313,  300,  315,  302,  308,  294,  295,  292,  292,  295,
      292,  289,    0,  288,  292,   56,  290,   40,   81,  294,

      287,   72,   82,  292,  380,  380,  334,  169,  214,  380,
        0,  176,  118,  380,  380,  285,  297,  292,  280,  109,
      294,  292,  288,  280,  286,  289,    0,  275,    0,  281,
      278,  267,  269,  271,  278,  264,  262,  262,  274,  264,
      268,  272,  274,  263,  307,  210,  380,    0,  262,    0,
        0,  253,  261,  250,  257,    0,    0,  251,  248,    0,
        0,  248,  248,  245,  257,  247,  251,  256,  255,  253,
      243,  248,    0,  236,  248,    0,    0,    0,  239,  240,
      241,  230,    0,  224,  226,    0,  234,  220,  219,  199,
      203,  205,    0,  196,  197,    0,  234,  171,  166,    0,

        0,  161,    0,    0,    0,    0,    0,    0,  159,  130,
       83,  164,   85,    0,   71,    0,   79,   72,  233,    0,
        0,    0,    0,  168,  172,  217,   84,  238,  242,  204,
      380,  264,  268,  272,  274,  278,  284
    } ;

static yyconst flex_int16_t yy_def[238] =
    {   0,
      231,    1,  231,  231,  231,  231,  231,  231,  232,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  233,  231,
      231,  231,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  231,  231,  231,
      231,  231,  232,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,   21,  231,  231,  231,  234,
       22,  231,  231,  231,  231,  231,  231,  233,  231,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,

      233,  233,  233,  233,  231,  231,  232,  231,  231,  231,
       65,  235,  234,  231,  231,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  231,  236,  231,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  237,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  237,  233,  233,  233,

      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  237,  233,  233,  233,  233,  233,  233,  237,  233,
      233,  233,  233,  237,  237,  237,  237,  237,  237,  237,
        0,  231,  231,  231,  231,  231,  231
    } ;

static yyconst flex_int16_t yy_nxt[449] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   22,   22,   22,   23,   24,   25,   26,   27,   28,
       29,   29,   29,   29,   29,   29,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   29,   40,   29,
       41,   29,   29,   29,   29,   42,   43,   44,   45,   46,
       47,   29,   29,   29,   48,   49,   50,   51,   56,   59,
       61,   63,   63,   63,   63,   63,   63,   63,   73,   74,
       76,   77,   90,   62,   60,   91,  134,   57,   65,  212,
       66,   66,   66,   66,   66,   66,   67,   85,   82,   87,

      231,   88,  131,  135,   68,   83,   86,   69,   69,   70,
       89,   84,   93,  132,   97,   98,  223,   68,  105,   94,
      140,  136,  222,   69,   99,  231,  221,  100,  141,  220,
      142,   69,  143,  218,   70,   65,  137,   71,   71,   71,
       71,   71,   71,   71,  108,  108,  108,  108,  108,  108,
      108,   68,  147,  147,   72,   72,  106,  112,  112,  112,
      112,  112,  112,  112,   68,  152,  153,  219,  147,  212,
       72,  228,  145,  212,  217,  229,  147,  212,   72,   63,
       63,   63,   63,   63,   63,   63,  108,  108,  108,  108,
      108,  108,  108,  109,  110,   65,  110,   67,   67,   67,

       67,   67,   67,   67,  216,  215,  109,  110,  110,  212,
      110,   68,  110,  111,  111,  111,  111,  111,  111,  111,
      230,  110,  212,  214,   68,  227,  110,  109,  110,  213,
      110,  146,  146,  146,  146,  146,  146,  146,  212,  212,
      109,  110,  110,  212,  110,  211,  110,  212,  210,  209,
      208,  224,  225,  226,  227,  110,  207,  225,  226,  227,
      110,  206,  226,  227,   53,  205,   53,   53,   53,   53,
       78,   78,   78,   78,  113,  113,  112,  204,  203,  112,
      146,  202,  201,  146,  197,  200,  197,  197,  197,  197,
      199,  198,  196,  195,  194,  193,  192,  191,  190,  189,

      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  170,  169,
      168,  167,  166,  165,  164,  163,  162,  161,  160,  159,
      158,  157,  156,  155,  154,  151,  150,  149,  148,  107,
      144,  139,  138,  133,  130,  129,  128,  127,  126,  125,
      124,  123,  122,  121,  120,  119,  118,  117,  116,  115,
      114,  107,  104,  103,  102,  101,   96,   95,   92,   81,
       80,   79,   75,   64,   58,   55,   54,   52,  231,    3,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,

      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231
    } ;

static yyconst flex_int16_t yy_chk[449] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   12,   16,
       18,   19,   19,   19,   19,   19,   19,   19,   25,   25,
       27,   27,   38,   18,   16,   38,   98,   12,   21,  227,
       21,   21,   21,   21,   21,   21,   21,   36,   35,   37,

       66,   37,   96,   98,   21,   35,   36,   21,   21,   21,
       37,   35,   40,   96,   43,   43,  218,   21,   49,   40,
      102,   99,  217,   21,   43,   66,  215,   43,  102,  213,
      103,   21,  103,  211,   21,   22,   99,   22,   22,   22,
       22,   22,   22,   22,   54,   54,   54,   54,   54,   54,
       54,   22,  113,  113,   22,   22,   49,   68,   68,   68,
       68,   68,   68,   68,   22,  120,  120,  212,  113,  212,
       22,  224,  108,  224,  210,  225,  113,  225,   22,   63,
       63,   63,   63,   63,   63,   63,  108,  108,  108,  108,
      108,  108,  108,   63,   63,   67,   63,   67,   67,   67,

       67,   67,   67,   67,  209,  202,   63,   63,  112,  230,
      112,   67,   63,   65,   65,   65,   65,   65,   65,   65,
      226,  112,  226,  199,   67,  230,  112,   65,   65,  198,
       65,  109,  109,  109,  109,  109,  109,  109,  219,  197,
       65,   65,  146,  228,  146,  195,   65,  229,  194,  192,
      191,  219,  219,  219,  219,  146,  190,  228,  228,  228,
      146,  189,  229,  229,  232,  188,  232,  232,  232,  232,
      233,  233,  233,  233,  234,  234,  235,  187,  185,  235,
      236,  184,  182,  236,  237,  181,  237,  237,  237,  237,
      180,  179,  175,  174,  172,  171,  170,  169,  168,  167,

      166,  165,  164,  163,  162,  159,  158,  155,  154,  153,
      152,  149,  145,  144,  143,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  133,  132,  131,  130,  128,  126,
      125,  124,  123,  122,  121,  119,  118,  117,  116,  107,
      104,  101,  100,   97,   95,   94,   92,   91,   90,   89,
       88,   87,   86,   85,   84,   83,   82,   81,   80,   77,
       73,   53,   47,   46,   45,   44,   42,   41,   39,   34,
       33,   32,   26,   20,   15,   11,   10,    8,    3,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,

      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tokeniser/tokeniser.l"
#line 3 "tokeniser/tokeniser.l"
#include <iostream>
#include <string>
#include <cstdlib>
enum token_type {_AUTO = 256, _BREAK, _CAS, _CHAR, _CONST, _CONTINUE, _DEFAULT, _DO, _DOUBLE, _ELSE, _ENUM, _EXTERN, _FLOAT, _FOR, _GOTO, _IF, _INT, _LONG, _REGISTER, _RETURN, _SHORT, _SIGNED, _SIZEOF, _STATIC, _STRUCT, _SWITCH, _TYPEDEF, _UNION, _UNSIGNED, _VOID, _VOLATILE, _WHILE, _ID, _ADD, _SUB, _MULT, _DIV, _MOD, _AND, _OR, _XOR, _LSHIFT, _RSHIFT, _ASSIGN, _ADDA, _SUBA, _MULTA, _DIVA, _MODA, _ANDA, _ORA, _XORA, _LSHIFTA, _RSHIFTA, _LAND, _LOR, _EQUAL, _NEQUAL, _LESSEQUAL, _GREATEQUAL, _LESSTHAN, _GREATTHAN, _BITCOMP, _COMP, _INC, _DEC, _COMMA, _CASE, _COND, _SEMI, _LPAR, _RPAR, _LCBRA, _RCBRA, _LBRAK, _RBRAK, _CDEC, _CFP, _CHEX, _COCT, _STR, _WSPACE, _NEWLINE, _PREP };
#line 645 "tokeniser/tokeniser.yy.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 28 "tokeniser/tokeniser.l"

#line 834 "tokeniser/tokeniser.yy.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 232 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 380 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 29 "tokeniser/tokeniser.l"
return _AUTO;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 30 "tokeniser/tokeniser.l"
return _BREAK;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 31 "tokeniser/tokeniser.l"
return _CAS;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 32 "tokeniser/tokeniser.l"
return _CHAR;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 33 "tokeniser/tokeniser.l"
return _CONST;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 34 "tokeniser/tokeniser.l"
return _CONTINUE;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 35 "tokeniser/tokeniser.l"
return _DEFAULT;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 36 "tokeniser/tokeniser.l"
return _DO;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 37 "tokeniser/tokeniser.l"
return _DOUBLE;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 38 "tokeniser/tokeniser.l"
return _ELSE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 39 "tokeniser/tokeniser.l"
return _ENUM;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 40 "tokeniser/tokeniser.l"
return _EXTERN;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 41 "tokeniser/tokeniser.l"
return _FLOAT;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 42 "tokeniser/tokeniser.l"
return _FOR;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 43 "tokeniser/tokeniser.l"
return _GOTO;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 44 "tokeniser/tokeniser.l"
return _IF;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 45 "tokeniser/tokeniser.l"
return _INT;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 46 "tokeniser/tokeniser.l"
return _LONG;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 47 "tokeniser/tokeniser.l"
return _REGISTER;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 48 "tokeniser/tokeniser.l"
return _RETURN;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 49 "tokeniser/tokeniser.l"
return _SHORT;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 50 "tokeniser/tokeniser.l"
return _SIGNED;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 51 "tokeniser/tokeniser.l"
return _SIZEOF;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 52 "tokeniser/tokeniser.l"
return _STATIC;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 53 "tokeniser/tokeniser.l"
return _STRUCT;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 54 "tokeniser/tokeniser.l"
return _SWITCH;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 55 "tokeniser/tokeniser.l"
return _TYPEDEF;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 56 "tokeniser/tokeniser.l"
return _UNION;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 57 "tokeniser/tokeniser.l"
return _UNSIGNED;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 58 "tokeniser/tokeniser.l"
return _VOID;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 59 "tokeniser/tokeniser.l"
return _VOLATILE;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 60 "tokeniser/tokeniser.l"
return _WHILE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 63 "tokeniser/tokeniser.l"
return _ID;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 66 "tokeniser/tokeniser.l"
return _ADD;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 67 "tokeniser/tokeniser.l"
return _SUB;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 68 "tokeniser/tokeniser.l"
return _MULT;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 69 "tokeniser/tokeniser.l"
return _DIV;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 70 "tokeniser/tokeniser.l"
return _MOD;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 72 "tokeniser/tokeniser.l"
return _AND;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 73 "tokeniser/tokeniser.l"
return _OR;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 74 "tokeniser/tokeniser.l"
return _XOR;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 75 "tokeniser/tokeniser.l"
return _LSHIFT;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 76 "tokeniser/tokeniser.l"
return _RSHIFT;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 78 "tokeniser/tokeniser.l"
return _ASSIGN;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 79 "tokeniser/tokeniser.l"
return _ADDA;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 80 "tokeniser/tokeniser.l"
return _SUBA;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 81 "tokeniser/tokeniser.l"
return _MULTA;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 82 "tokeniser/tokeniser.l"
return _DIVA;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 83 "tokeniser/tokeniser.l"
return _MODA;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 84 "tokeniser/tokeniser.l"
return _ANDA;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 85 "tokeniser/tokeniser.l"
return _ORA;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 86 "tokeniser/tokeniser.l"
return _XORA;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 87 "tokeniser/tokeniser.l"
return _LSHIFTA;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 88 "tokeniser/tokeniser.l"
return _RSHIFTA;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 90 "tokeniser/tokeniser.l"
return _LAND;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 91 "tokeniser/tokeniser.l"
return _LOR;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 92 "tokeniser/tokeniser.l"
return _EQUAL;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 93 "tokeniser/tokeniser.l"
return _NEQUAL;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 94 "tokeniser/tokeniser.l"
return _LESSEQUAL;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 95 "tokeniser/tokeniser.l"
return _GREATEQUAL;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 96 "tokeniser/tokeniser.l"
return _LESSTHAN;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 97 "tokeniser/tokeniser.l"
return _GREATTHAN;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 99 "tokeniser/tokeniser.l"
return _BITCOMP;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 100 "tokeniser/tokeniser.l"
return _COMP;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 101 "tokeniser/tokeniser.l"
return _INC;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 102 "tokeniser/tokeniser.l"
return _DEC;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 104 "tokeniser/tokeniser.l"
return _COMMA;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 105 "tokeniser/tokeniser.l"
return _CASE;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 106 "tokeniser/tokeniser.l"
return _COND;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 107 "tokeniser/tokeniser.l"
return _SEMI;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 109 "tokeniser/tokeniser.l"
return _LPAR;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 110 "tokeniser/tokeniser.l"
return _RPAR;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 111 "tokeniser/tokeniser.l"
return _LCBRA;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 112 "tokeniser/tokeniser.l"
return _RCBRA;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 113 "tokeniser/tokeniser.l"
return _LBRAK;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 114 "tokeniser/tokeniser.l"
return _RBRAK;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 117 "tokeniser/tokeniser.l"
return _CDEC;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 118 "tokeniser/tokeniser.l"
return _CFP;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 119 "tokeniser/tokeniser.l"
return _CHEX;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 120 "tokeniser/tokeniser.l"
return _COCT;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 123 "tokeniser/tokeniser.l"
return _STR;
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 126 "tokeniser/tokeniser.l"
return _NEWLINE;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 127 "tokeniser/tokeniser.l"

	YY_BREAK
case 84:
YY_RULE_SETUP
#line 128 "tokeniser/tokeniser.l"

	YY_BREAK
case 85:
YY_RULE_SETUP
#line 129 "tokeniser/tokeniser.l"
return _PREP;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 131 "tokeniser/tokeniser.l"
ECHO;
	YY_BREAK
#line 1348 "tokeniser/tokeniser.yy.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 232 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 232 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 231);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 131 "tokeniser/tokeniser.l"



int main()
{
	using namespace std;

	int line_num = 1;
	int source_line = 0;
	string source_file;

	int ttcode = yylex();
	
	while(ttcode != 0)
	{
		switch(ttcode)
		{
			case _AUTO:
				cout << yytext << " Keyword T_AUTO " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _BREAK:
				cout << yytext << " Keyword T_BREAK " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _CAS:
				cout << yytext << " Keyword T_CASE " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _CHAR:
				cout << yytext << " Keyword T_CHAR " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _CONST:
				cout << yytext << " Keyword T_CONST " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _CONTINUE:
				cout << yytext << " Keyword T_CONTINUE " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _DEFAULT:
				cout << yytext << " Keyword T_DEFAULT " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _DO:
				cout << yytext << " Keyword T_DO " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _DOUBLE:
				cout << yytext << " Keyword T_DOUBLE " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _ELSE:
				cout << yytext << " Keyword T_ELSE " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _ENUM:
				cout << yytext << " Keyword T_ENUM " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _EXTERN:
				cout << yytext << " Keyword T_EXTERN " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _FLOAT:
				cout << yytext << " Keyword T_FLOAT " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _FOR:
				cout << yytext << " Keyword T_FOR " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _GOTO:
				cout << yytext << " Keyword T_GOTO " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _IF:
				cout << yytext << " Keyword T_IF " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _INT:
				cout << yytext << " Keyword T_INT " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _LONG:
				cout << yytext << " Keyword T_LONG " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _REGISTER:
				cout << yytext << " Keyword T_REGISTER " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _RETURN:
				cout << yytext << " Keyword T_RETURN " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _SHORT:
				cout << yytext << " Keyword T_SHORT " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _SIGNED:
				cout << yytext << " Keyword T_SIGNED " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _SIZEOF:
				cout << yytext << " Keyword T_SIZEOF " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _STATIC:
				cout << yytext << " Keyword T_STATIC " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _STRUCT:
				cout << yytext << " Keyword T_STRUCT " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _SWITCH:
				cout << yytext << " Keyword T_SWITCH " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _TYPEDEF:
				cout << yytext << " Keyword T_TYPEDEF " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _UNION:
				cout << yytext << " Keyword T_UNION " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _UNSIGNED:
				cout << yytext << " Keyword T_UNSIGNED " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _VOID:
				cout << yytext << " Keyword T_VOID " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _VOLATILE:
				cout << yytext << " Keyword T_VOLATILE " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _WHILE:
				cout << yytext << " Keyword T_WHILE " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _ID:
				cout << yytext << " Identifier T_ID " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _ADD:
				cout << yytext << " Operator T_ADD " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _SUB:
				cout << yytext << " Operator T_SUB " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _MULT:
				cout << yytext << " Operator T_MULT " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _DIV:
				cout << yytext << " Operator T_DIV " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _MOD:
				cout << yytext << " Operator T_MOD " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _AND:
				cout << yytext << " Operator T_AND " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _OR:
				cout << yytext << " Operator T_OR " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _XOR:
				cout << yytext << " Operator T_XOR " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _LSHIFT:
				cout << yytext << " Operator T_LSHIFT " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _RSHIFT:
				cout << yytext << " Operator T_RSHIFT " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _ASSIGN:
				cout << yytext << " Operator T_ASSIGN " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _ADDA:
				cout << yytext << " Operator T_ADDA " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _SUBA:
				cout << yytext << " Operator T_SUBA " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _MULTA:
				cout << yytext << " Operator T_MULTA " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _DIVA:
				cout << yytext << " Operator T_DIVA " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _MODA:
				cout << yytext << " Operator T_MODA " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _ANDA:
				cout << yytext << " Operator T_ANDA " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _ORA:
				cout << yytext << " Operator T_ORA " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _XORA:
				cout << yytext << " Operator T_XORA " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _LSHIFTA:
				cout << yytext << " Operator T_LSHIFTA " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _RSHIFTA:
				cout << yytext << " Operator T_RSHIFTA " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _LAND:
				cout << yytext << " Operator T_LAND " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _LOR:
				cout << yytext << " Operator T_LOR " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _EQUAL:
				cout << yytext << " Operator T_EQUAL " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _NEQUAL:
				cout << yytext << " Operator T_NEQUAL " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _LESSEQUAL:
				cout << yytext << " Operator T_LESSEQUAL " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _GREATEQUAL:
				cout << yytext << " Operator T_GREATEQUAL " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _LESSTHAN:
				cout << yytext << " Operator T_LESSTHAN " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _GREATTHAN:
				cout << yytext << " Operator T_GREATTHAN " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _BITCOMP:
				cout << yytext << " Operator T_BITCOMP " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _COMP:
				cout << yytext << " Operator T_COMP " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _INC:
				cout << yytext << " Operator T_INC " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _DEC:
				cout << yytext << " Operator T_DEC " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _COMMA:
				cout << yytext << " Operator T_COMMA " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _CASE:
				cout << yytext << " Operator T_CASE " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _COND:
				cout << yytext << " Operator T_COND " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _SEMI:
				cout << yytext << " Operator T_SEMI " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _LPAR:
				cout << yytext << " Operator T_LPAR " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _RPAR:
				cout << yytext << " Operator T_RPAR " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _LCBRA:
				cout << yytext << " Operator T_LBRA " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _RCBRA:
				cout << yytext << " Operator T_RBRA " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _LBRAK:
				cout << yytext << " Operator T_LBRAK " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _RBRAK:
				cout << yytext << " Operator T_RBRAK " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _CDEC:
				cout << yytext << " Constant T_CDEC " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _CFP:
				cout << yytext << " Constant T_CFP " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _CHEX:
				cout << yytext << " Constant T_CHEX " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _COCT:
				cout << yytext << " Constant T_COCT " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _STR:
				cout << yytext << " StringLiteral T_STR " << line_num << " " << source_file << " " << source_line << endl;
				break;
			case _NEWLINE:
				line_num++;
				source_line++;
				break;
			case _PREP:
			{
				string prep(yytext);
				// find the first "
				size_t first = prep.find('"');
				// find the last "
				size_t last = prep.rfind('"');
				// erase the flags
				prep.erase(last);
				// get just the source file
				source_file = prep.substr(first + 1, last - first - 1);
				prep.erase(first - 1);
				// get just the source line
				string num = prep.substr(2);
				source_line = strtol(num.c_str(), NULL, 10);
				source_line--;
			}
				break;
			default:
				cout << yytext << " invalid T_INVALID " << line_num << " " << source_file << " " << source_line << endl;
				break;
		}

		ttcode = yylex();
	}

	return 0;
}

